quran/quran.com-frontend

- src/scripts/components/header/MasterHeader.js
- src/scripts/routes/Surah.js
- src/styles/components/MasterHeader.scss
Also removed pager options in the same manner. If the user is at Al-Faatihah or An-Naas they will not be able to click a non-existing link, breaking the app in some instances.
The words "NEXT CHAPTER and "PREVIOUS CHAPTER" have been changed here for consistency reasons, as the bottom of the page reads "Surah".
> Removes hyperlink for previous surah & next surah in the header. 

- src/scripts/components/header/ContentDropdown.js
Deselecting all translations enters reading mode, manually re-entering a translation again brings back the translation view.
> Clearing all translations enters reading mode

- src/scripts/components/header/ContentDropdown.js
> Sort translation languages list in alphabetical order

- .gitignore
- Dockerfile
Requires .ssh key configured and present in the current working
directory. This won't be checked in for security purposes.
> Upload js and css to cdn after building the image.

- README.md
Add Dependency Status to Readme for easy monitor outdated dependencies.
> Add Dependency Status to Readme

- package.json
- src/scripts/components/Application.js
- src/scripts/components/Html.js
- src/scripts/config.js
- src/scripts/routes/About.js
- src/scripts/routes/Index.js
- src/scripts/routes/Search.js
- src/scripts/routes/Surah.js
> Solves Add helmet

- src/config.js
Setting the theme-color meta-tag allows for the title bar to be colored
on Chrome for Android.
> Support Chrome's theme-color

- karma.conf.js
- src/components/LazyLoad/index.js
- src/components/LazyLoad/spec.js
- src/containers/Surah/index.js
- src/redux/modules/ayahs.js
Fixes https://github.com/quran/quran.com-frontend/issues/286
> End of surah loading

- src/components/SurahInfo/index.js
- src/components/SurahInfo/style.scss
Fixes https://github.com/quran/quran.com-frontend/issues/326
> CDN images for surahinfo

- .env
- .gitignore
- src/containers/Error/index.js
- src/containers/Home/index.js
- src/containers/Surah/index.js
- src/routes.js
- src/utils/checkValidSurah.js
Handles invalid surah by creating onEnter #248
Creates an error container
> Fixes #248 Out of range bug

- .editorconfig
- .env
- client.js
- package.json
- server.js
- src/components/Ayah/index.js
- src/components/FontStyles/index.js
- src/components/FontStyles/selector.js
- src/config.js
- src/containers/App/index.js
- src/containers/Search/index.js
- src/containers/Surah/connect.js
- src/containers/Surah/index.js
- src/helpers/Html.js
- src/helpers/buildFontFaces.js
- src/redux/modules/ayahs.js
- src/redux/modules/fontFaces.js
- src/redux/modules/reducer.js
- src/redux/modules/searchResults.js
Fixes https://github.com/quran/quran.com-frontend/issues/268
> Fout fonts

- src/routes.js
> #372 colon separated surah/ayah

- src/components/Audioplayer/style.scss
- src/components/Ayah/index.js
- src/components/Share/index.js
- src/components/Share/style.scss
- src/components/SurahInfo/style.scss
- src/containers/Home/style.scss
- src/containers/Surah/index.js
- Fix audio player playing text
- Remove unneeded padding on mobile
- Hide Share on mobile devices (native share is built into the browsers)
Images of style bugs:
> - ayah's have link (discuss, maybe not needed)

- package.json
- src/containers/Surah/Title/index.js
- src/containers/Surah/Title/spec.js
Fixed + unit tests
closes #398
> closes #398 - "Previous/Next Surah" when reading first/last surah

- src/config.js
> Basmallah url should not force http

- package.json
babel-preset-es2015 6.13.1 causes issues with
babel-preset-es2015-webpack, so this freezes the dependency of
babel-preset-es2105 to 6.9.0.
> Fix build issue with babel-preset-es2015

- CONTRIBUTING.md
> Contributing guide updated

- package.json
Express 4.3.2, which we use, has a vulnerability. The stable version
should not have this vulnerability (the version we are using is very
old, from 2014).
> Upgrade express to the latest stable version

- docker/supervisord.conf
Setting -i of 0 lets pm2 choose to start as many workers as there are
cores, which is better than manually choosing 4. Fixes #445.
> Let pm2 automagically choose the number of workers

- src/components/Audioplayer/index.js
- src/redux/modules/audioplayer.js
Previously, we had to check whether or not audio was of a supported
format, since most of our audio files were ogg only (which wouldn't work
on Safari and other browsers). Since we are now using mp3s for
everything, we no longer need these checks.
> Remove supported check for audio

- src/components/ContentDropdown/index.js
Sort languages in the dropdown alphabetically.
Issue: https://github.com/quran/quran.com-frontend/issues/57
> Sort language in dropdown alphabetically

- src/client.js
- src/components/Ayah/index.js
- src/components/Ayah/style.scss
- src/components/Line/index.js
- src/styles/partials/_tooltip.scss
I replaced the Ayah tooltip from using jQuery & bootstrap tooltips to use just CSS. I only managed to find it used in two places `<Ayah />` & `<Line />` so if it's used somewhere else please let me know.
**Some stuff I noticed while working on this**
- CSS is done in multiple different ways that it's very hard to reason about things. `Normal Sass, CSS modules & some bootstrap magic`
- Can we get rid of Bootstrap completely? for layout components this is very lightweight & doesn't add load of CSS http://jxnblk.com/rebass/
- No usage of `dir="rtl"` or `lang="ar"` attributes on any HTML which kind of forces some kind of CSS hacks to align text & stuff.
> Replace bootstrap tooltips with CSS ones

- src/components/Ayah/index.js
> #461 Adding verse number to tooltip

- src/containers/Search/index.js
Looks like an easy fix by just adding the missing tooltip prop in `Ayah` component.
> Issue  #472: Added tooltip prop for Ayah component in Search page

- src/containers/App/index.js
- src/containers/App/style.scss
This PR closes [issue-487](https://github.com/quran/quran.com-frontend/issues/487)
Footer layout is improved.
For larger screens:
For medium size screens:
For small screen:
While running test, I got the following test errors which I don't think are because of the changes that I did.
```
11 11 2016 05:22:15.080:WARN [karma]: No captured browser, open http://localhost:9876/
11 11 2016 05:22:15.090:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
11 11 2016 05:22:15.090:INFO [launcher]: Launching browser Chrome with unlimited concurrency
11 11 2016 05:22:15.212:INFO [launcher]: Starting browser Chrome
11 11 2016 05:22:17.006:INFO [Chrome 54.0.2840 (Linux 0.0.0)]: Connected on socket /#t_QbTXeWLNIgMHKEAAAA with id 5468706
LOG: ClientRect{}
ERROR: 'Warning: Failed propType: …
```
> Footer links are restored and footer layout is improved.

- .env
- .eslintrc
- Dockerfile
- src/client.js
- src/components/FacebookButton/index.js
- src/components/IndexHeader/Nav/index.js
- src/components/IndexHeader/index.js
- src/components/QuranNav/index.js
- src/components/QuranNav/style.scss
- src/config.js
- src/containers/Login/index.js
- src/containers/Profile/index.js
- src/containers/Profile/style.scss
- src/containers/Surah/Header/index.js
- src/helpers/ApiClient.js
- src/redux/actions/auth.js
- src/redux/constants/auth.js
- src/redux/modules/auth.js
- src/redux/modules/reducer.js
- src/routes.js
- src/server.js
- src/server/config/express.js
- src/styles/components/MasterHeader.scss
- src/styles/variables.scss
- src/types/userType.js
- webpack/dev.config.js
> User authentication and profile

- .env
- src/components/Ayah/index.js
- src/containers/App/index.js
- src/containers/Surah/index.js
- src/redux/actions/media.js
- src/redux/constants/media.js
- src/redux/modules/media.js
- src/redux/modules/reducer.js
- webpack/prod.config.js
@Bayyinah has given us some videos to try out. For surah 1 only.
This is adding them and playing the videos inside a modal
> Adding media and modal

- src/server/config/express.js
node-http-proxy was putting a host header with the current server name,
which was thus causing nginx on the receiving end to send the request to
the default handler (or the first one). This patch asks node-http-proxy
to rewrite the host and port, and also to change the origin of the host
header to onequran's url.
> Fix node-http-proxy host in proxy request

- Dockerfile
- src/components/Ayah/index.js
- src/components/Sidebar/index.js
- src/components/Sidebar/style.scss
- src/containers/App/index.js
- src/containers/Home/index.js
- src/containers/Surah/Header/index.js
- src/containers/Surah/Header/style.scss
- src/containers/Surah/index.js
- src/containers/Surah/style.scss
- src/helpers/ApiClient.js
- src/server/config/express.js
- src/styles/bootstrap.config.js
- src/styles/main.scss
- src/styles/partials/_search-input.scss
- src/styles/partials/_surah-title.scss
- src/styles/partials/_tooltip.scss
- webpack/prod.config.js
For some reason, the Dockerfile envs are not getting picked up but rather .env is persisting
> Env problems

- src/components/Ayah/index.js
- src/components/Home/QuickSurahs/spec.js
- src/containers/Surah/index.js
- src/styles/partials/_tooltip.scss
- src/utils/bindTooltip.js
- src/utils/getOffset.js
This PR aims to remove [issue-496](https://github.com/quran/quran.com-frontend/issues/496).
Tooltip working and code can be seen [here.](http://codepen.io/arshdkhn1/pen/aBBXBq)
Test logs:
```
karma start
18 11 2016 17:47:27.657:WARN [karma]: No captured browser, open http://localhost:9876/
18 11 2016 17:47:27.690:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
18 11 2016 17:47:27.690:INFO [launcher]: Launching browser Chrome with unlimited concurrency
18 11 2016 17:47:27.834:INFO [launcher]: Starting browser Chrome
18 11 2016 17:48:27.835:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
18 11 2016 17:48:29.836:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
18 11 2016 17:48:33.929:INFO [launcher]: Trying to start Chrome again (1/2). …
```
> tooltip fix

- src/containers/Surah/index.js
This should resolve https://github.com/quran/quran.com-frontend/issues/485
The issue is because it compares `ayahIds.size` with `surah.ayat`.
`Ayahids` is a subset of all ayah, in this case the size is 7 and total ayah in An-nisa is 176 so `Loading` is always displayed.
Fixing it by comparing the last ayah in array with `surah.ayat`
Head to surah An-Nisa quran.com/4/170 and see if loading is still displayed
> Fix loading always shows when reaching the end of the surah

- src/client.js
- src/components/Audioplayer/index.js
- src/components/Ayah/index.js
- src/components/Loader/index.js
- src/components/Loader/style.scss
- src/components/NoScriptWarning/index.js
- src/components/SearchAutocomplete/index.js
- src/components/SearchInput/index.js
- src/containers/Search/index.js
- src/containers/Surah/connect.js
- src/containers/Surah/index.js
- src/containers/Surah/style.scss
- src/redux/modules/audioplayer.js
- static/quran-service-worker.js
I have observed too many times where users click a surah and expect something to happen. And something does after all the data is resolved and a transition happens. That's not a good experience for users.
- Transitions on the client and shows loader until data is resolved
- Fixes Search Page + transitions
- Adds a new loader. The old one was great but the colors weren't even matching
> Loading transition on the client

- src/containers/Surah/index.js
> Fixes #562 Highlight when playing

- src/components/Loader/index.js
- src/containers/Surah/index.js
- src/containers/Surah/style.scss
Fixes #557 
Changed the loader - the previous one was too large and thus created an element larger than the screen.
> Fixes #557 Scrollbars bouncing

- src/config.js
- src/helpers/Html.js
- src/styles/variables.scss
intl pollyfil should included before our main js, opening pr for testing the impact of moving js into bottom.
> Improved time to first paint 

- src/components/Footer/index.js
- src/components/GlobalSidebar/index.js
- src/components/SettingsModal/index.js
- src/locale/ar.js
- src/locale/en.js
- src/locale/ur.js
> Fixes #595, #601 Add translations for settings in sidebar

- .babelrc
- bin/server.js
- src/components/GlobalNav/Surah/index.js
- src/containers/Search/index.js
- src/containers/Surah/Header/index.js
- src/locale/ar.js
- src/locale/en.js
- src/locale/ur.js
- src/redux/create.js
- src/routes.js
- src/styles/partials/_search-input.scss
> Fixes staging and Fixes #593

- src/components/Audioplayer/RepeatDropdown/index.js
These are fixes for a few bugs in the audio player range component.
* When the user selects a verse in the _from_ component, _to_ is set to _from_'s value + 3. This leads to _to_ going beyond the last verse if the last verse is selected as _from_.
* When the user selects a verse in _from_, the _to_ options are incorrectly calculated beyond the number of verses in the surah.
Assumptions:
- The props.surah.ayat number is 1 or more. 
- A surah with 10 verses will have surah.ayat == 10.
- From should not have an option where the option's value == surah.ayat.
- To should not have an option where the option's value == 1.
I wanted to add a test for this but I didn't see an example where a similar sort was done. I also wanted to run the current tests but I couldn't get them working.
> Fixes for repeat range bugs

- src/components/IndexHeader/index.js
- src/components/IndexHeader/style.scss
- src/styles/partials/_index-header.scss
Salaam. The lack of top margin on the index header logo was flaring up my OCD (sorry) so I've made the necessary changes to fix this. It is a design change so if you like it the way it is that's cool, have a look at the image below.
Will be looking at the other issues and picking up what I can, I have experience in Node.js, React/Native, Sass etc.
> Added top margin to the index header logo

- src/components/Word/index.js
- src/types/wordType.js
Double click does not work on mobile. We already have `onClick` for segments. Thoughts? 
I think we should remove the click for segments and just use the word audio
> Fixes #659 Double Click for Word Audio

- .env
- src/components/Home/SurahsList/index.js
- src/components/Translation/index.js
- src/components/Translation/style.scss
- src/components/Verse/index.js
- src/components/Verse/style.scss
- src/components/Word/index.js
- src/config.js
- src/containers/App/index.js
- src/redux/actions/verses.js
- src/redux/modules/options.js
- src/styles/main.scss
- src/types/index.js
- src/types/translationType.js
- src/types/verseType.js
> Surah page

- src/components/Audioplayer/index.js
- src/redux/schemas.js
- src/utils/scroller.js
This fixes #637, where scrolling lags 1 verse behind the player's current position. It also fixes the scroll alignment, and handles cases where the verse is already fully visible, or too big to fit on the screen.
A v3 API change caused ayah object keys to be just the ayah number, instead of `surah:ayah`. I don't know if the change was intentional, but it broke a lot of stuff (most notably, the audio player).
> Fix autoscroll jankiness

- src/components/SurahInfo/index.js
- src/helpers/ApiClient.js
Need to fix https://github.com/quran/quran.com-api/issues/125 before merging this
> added language in every api call

- src/containers/Surah/index.js
- src/helpers/buildSegments.js
- src/locale/ar.js
- src/locale/en.js
- src/locale/fr.js
- src/locale/id.js
- src/locale/tr.js
- src/locale/ur.js
- src/redux/modules/fontFaces.js
> Fix non existant ayat

- src/components/Line/index.js
- src/components/PageView/index.js
> use text fonts for render page mode #689

- src/components/SurahInfo/index.js
- src/containers/ChapterInfo/index.js
- src/containers/Surah/connect.js
- src/containers/Surah/index.js
- src/helpers/ApiClient.js
- src/locale/ar.js
- src/locale/en.js
- src/locale/fr.js
- src/locale/id.js
- src/locale/tr.js
- src/locale/ur.js
- src/redux/actions/chapters.js
- src/redux/modules/chapters.js
- src/routes.js
- src/server/config/sitemap.js
- src/types/index.js
- src/types/infoType.js
> Surah info SEO

- src/components/Audioplayer/Segments/index.js
- src/components/Audioplayer/index.js
- src/components/ContentDropdown/index.js
- src/components/ReciterDropdown/index.js
- src/components/Verse/index.js
- src/components/Verse/style.scss
- src/components/Word/index.js
- src/containers/Search/index.js
> Fix staging

- src/components/Audioplayer/index.js
- src/components/GlobalNav/Surah/index.js
- src/components/SurahsDropdown/index.js
- src/components/VersesDropdown/index.js
- src/components/VersesDropdown/style.scss
- src/containers/Surah/index.js
- src/redux/actions/spec.js
- src/redux/actions/verses.js
- src/styles/partials/_dropdown.scss
- src/styles/partials/_search-input.scss
> Fixes #654 Verses dropdown

- src/config.js
> Fixes #544 local for google index

- package.json
- src/containers/App/index.js
- src/containers/Home/index.js
- src/containers/Surah/index.js
- yarn.lock
Premise: `renderToString` is really slow, and even slower when there are more trees. Thus, if we get rid of components that require user interactions or do not contain links to render only on client, we can save some time! 
I am thinking I should make a util for this. Thoughts?
> Render less until client

- src/components/Line/index.js
At issue #753 
At line 69 ayah was prepended to the name attribute when the word verse should have been. Autoscroll is now working but it's still not perfect.
> Changed the name attribute to fix auto-scrolling

- src/components/Settings/TranslationsDropdown/index.js
Add else condition for ` translationOptions.length`
> Bug fix for issue #835

- src/components/Audioplayer/index.js
The pull request is addressed to close the [issue raised here](https://github.com/quran/quran.com-frontend/issues/786)
On Chrome, the ``` play() ``` method on an HTML Media Element returns a promise.
Since, the play method is asynchronous, if ``` pause() ``` method is called/triggered while a call to ``` play() ``` is in progress, Chrome throws an error stating
``` The play() request was interrupted by a call to pause() ```
The error thrown by Chrome doesn't break anything, it is just logged on the console.
On Browsers that return a promise, we can chain the play promise to catch any errors and ignore them.
> Remove "The play() request was interrupted by a call to pause()"

- src/server/config/apple-app-site-association.json
- src/server/config/express.js
associated with https://github.com/quran/quran-ios/issues/195
1. promoting the App
2. Linking between our apps (quranicaudio is coming soon(TM)
> add  site association for ios universal linking

- src/components/Verse/index.js
- src/config.js
- src/locale/sq.js
- src/redux/actions/media.js
- src/redux/modules/media.js
> Add .sq locale

- package.json
- src/components/Copy/index.js
- src/components/Footer/index.js
- src/components/GlobalNav/index.js
- src/components/GlobalSidebar/index.js
- src/components/Home/JuzList/index.js
- src/components/Home/QuickSurahs/index.js
- src/components/Home/SurahsList/index.js
- src/components/IndexHeader/index.js
- src/components/LocaleSwitcher/index.js
- src/components/Share/index.js
- src/events.js
- src/helpers/Html.js
- src/helpers/metrics.js
- src/server.js
This is a way to standardize the way we log events and name them. As noted in the file:
The goal for developers is to have them call:
```
FOOTER_EVENTS.CLICK.AUDIO;
```
and returns
```
{ NAME: 'Footer', ACTION: 'Click', LABEL: 'Audio' }
```
Better yet, calling
```
FOOTER_EVENTS.CLICK.AUDIO.PROPS;
```
will give you all the props needed for react-metrics to pass the correct data to google analytics.
> Events constants and logging

- .env
- package.json
- src/config.js
- src/helpers/Html.js
- src/helpers/fontsStyle.js
- src/styles/main.scss
- src/styles/partials/_dropdown.scss
- webpack/dev.config.js
- webpack/prod.config.js
Moving the fonts setup to be in javascript and bootstrapped in the html file
> Move fonts css to be javascript

- package-lock.json
- src/components/NotFound/index.js
- src/components/Status/index.js
- src/components/Status/spec.js
- src/locale/en.js
- src/routes.js
Currently, we don't return 404 when you go to not found urls. Example of that is `http://localhost:8000/public/dist/main.js`
> Return 404 when no routes found

- .babelrc
- package-lock.json
- package.json
- src/containers/ChapterInfo/index.js
- src/containers/Surah/index.js
- src/containers/VerseTafsir/index.js
- webpack/dev.config.js
Remove babel-typecheck. If we want to do typecheck, then we should explore typescript or flowtype. This package has not been updated in 2 years.
> Remove babel-typecheck

- package-lock.json
- package.json
Upgraded react-metrics to 2.4.1 which fixed double metrics inserting bug. This bug was breaking the whole app.
> Fixed metrics 

- src/components/Footer/index.js
Remove CSS prefix from styled components, because the CSS rules in Styled Components are automatically vendor prefixed.
Fixes #947
N/A
> Remove CSS prefix from styled components

- src/components/Share.tsx
- src/components/verse/Controls.tsx
This PR should make the Facebook and Twitter icons inline so that it looks much better.
**Before**
**After**
> Share icons to be inline

- src/components/ChapterInfoPanel.tsx
- src/components/FontText.tsx
- src/components/Line.tsx
- src/components/Share.tsx
- src/components/Verse.tsx
- src/components/Word.tsx
- src/components/audioplayer/Track.tsx
- src/components/audioplayer/Wrapper.tsx
- src/components/dls/ButtonLink.tsx
- src/components/verse/Badge.tsx
- src/helpers/fontsStyle.ts
- src/redux/reducers/audioplayer.ts
- src/redux/reducers/chapterInfos.ts
- src/redux/reducers/footNotes.ts
- src/redux/reducers/lines.ts
- src/redux/reducers/options.ts
- src/redux/reducers/search.ts
- src/styles/main.global.scss
> General cleanup

- .env
- src/components/TranslationNode.tsx
- src/components/Word.tsx
- src/redux/reducers/settings.ts
- Fixed wbw audio 
- Minor improvements for copying the ayah text
- Default translation was removed from staging, new translation has different id now 
> Fixed WBW audio

- src/config.js
- src/containers/ChapterInfo/index.js
- src/containers/Surah/index.js
1. Removed the canonical url property `og:url` which made Facebook and other crawlers always fetch the meta tags for https://quran.com instead of the desired path.
2. Added dynamic open-graph images that fetch image previews based on the content.
@mmahalwy I don't have the API running locally so haven't been able to test the changes. Let's get it up on staging and give it a test before we deploy it to prod.
> Add dynamic og:image and remove canonical urls
