- src/scripts/routes/About.js
User able to click a link to see the Qur'an Wikipedia page.
> Added link to Qur'an Wikipedia article in the About page.

- src/scripts/components/Application.js
- src/scripts/configs/routes.js
- src/scripts/stores/ApplicationStore.js
> Fixed index page title

- src/styles/partials/_search-input.scss
> Search bar fixes css

- package.json
- src/scripts/components/header/ContentDropdown.js
- src/scripts/routes/Contact.js
- src/scripts/stores/AudioplayerStore.js
> Transliteration added

- package.json
- src/scripts/components/header/FontSizeInput.js
- src/scripts/components/header/IndexHeader.js
- src/scripts/components/header/IndexHeaderNav.js
- src/scripts/components/header/MasterHeader.js
- src/scripts/components/header/SearchInput.js
- src/scripts/components/surah/Ayah.js
> Fixing eslint

- src/scripts/components/audioplayer/Audioplayer.js
- src/styles/components/Audioplayer.scss
The purpose is many people complain audio is not working but in fact it's actually just not loaded! Now left a loading icon until the audio is loaded which is conveniently really fast these days :)
> 97591748 Audioplayer loading icon until loaded.

- src/scripts/routes/About.js
Added links for: 
>Tanzil, QuranComplex, Zekr and Online Qur'an Project. 
Also a direct link for "visit the Contact page"
> Added links to About

- src/styles/components/SurahNav.scss
@mmahalwy Fixes Surat An-Naas & the scrollbar being hidden when .shrink is active ( issue #33 ).
> Surah 114 & scrollbar visible in '.shrink'

- src/scripts/components/header/InformationToggle.js
- src/scripts/components/header/NavCollapseToggle.js
- src/scripts/components/header/ReadingModeToggle.js
Added titles to show more information when hovering over icons.
> Anchor Titles for Icons

- src/scripts/routes/Donations.js
Fixes https://github.com/quran/quran.com-frontend/issues/129
> Remove "stronger impact" hyperlink

- .gitignore
- src/scripts/components/Application.js
Another minor patch :smile: 
Since they're external links, it's best to open them in a new tab instead of loading them in the same window.
> Open footer links in a new tab/window

- src/scripts/components/surah/Ayah.js
- tests/client/stores/UserStore.spec.js
> Highlight font

- src/scripts/components/audioplayer/Audioplayer.js
- src/scripts/stores/AudioplayerStore.js
- tests/client/actions/AudioplayerActions.spec.js
The audioplayer would continue to play when you visit another page or go back to the surahs list. Now, when that happens, I want to stop and destroy the audio.
> Fixed audio loading

- src/scripts/routes/Surah.js
People complained about this alot, you get to the end of the surah and it still says loading!
> Loading fixed at bottom of surah

- src/scripts/routes/Donations.js
- src/scripts/routes/Surah.js
- src/scripts/stores/AyahsStore.js
@ahmedre as per your request :)
> Load more and contributions added

- src/scripts/components/header/SearchInput.js
> Fix #143: prevent searching empty field

- src/scripts/routes/Surah.js
> Fixes #133: Load up to 10 previous ayahs

- src/components/PageBreak/index.js
- src/components/VersesDropdown/index.js
- src/containers/Surah/index.js
- src/redux/modules/lines.js
- src/scripts/components/surah/Line.js
- src/styles/components/Ayah.scss
> Reading mode fixed

- package.json
- src/components/FontSizeDropdown/index.js
- src/containers/Search/index.js
- src/containers/Surah/Title/index.js
- src/helpers/metrics.js
- src/scripts/components/Application.js
- src/scripts/components/Html.js
- src/scripts/components/header/IndexHeader.js
- src/scripts/components/header/IndexHeaderNav.js
- src/scripts/components/header/SearchInput.js
- src/scripts/components/surah/Ayah.js
> Added metrics

- src/components/Audioplayer/index.js
- src/components/Audioplayer/style.scss
- src/redux/modules/audioplayer.js
> adds an option to scroll to the playing audio

- src/components/Audioplayer/Track/index.js
- src/components/Audioplayer/index.js
- src/components/VersesDropdown/index.js
- src/containers/Surah/index.js
- src/helpers/buildAudio.js
- src/redux/modules/audioplayer.js
- src/redux/modules/ayahs.js
@mmahalwy checkout this experimental branch, it just links the verse dropdown with the player which in my opinion feels a lot more useful and natural but it does something which you said we didn't want to do, which is set a general current ayah in state
> fixes current ayah behavior with verses dropdown and player

- src/components/Audioplayer/index.js
- src/containers/Surah/index.js
- src/scripts/utils/scroller.js
@mmahalwy please review this too
> factors out the react-scroll module

- src/components/SearchAutocomplete/index.js
- src/components/SearchAutocomplete/style.scss
- src/scripts/components/header/SearchInput.js
@mmahalwy please review; also how do I run lint?
> Suggest improvement

- karma.conf.js
- package.json
- src/components/ContentDropdown/index.js
- src/components/ContentDropdown/spec.js
- src/components/PageBreak/index.js
- src/components/PageBreak/spec.js
- src/containers/Surah/index.js
I will spend more time over the weekend writing more tests inshallah
> Add some tests with enzyme

- package.json
I am getting `npm ERR! code EPEERINVALID`. This fixes this issue.
> Upgrade ReactJS to version 0.14.8

- karma.conf.js
My IDE, Visual Studio Code lament about these lint issues.
In this PR:
> Fix lint issues

- README.md
> Update readme to help new developers

- src/components/SearchAutocomplete/index.js
> Autocomplete pointing to v2 suggest

- README.md
> correct waffle url.

- src/containers/Surah/connect.js
- src/containers/Surah/index.js
> Extract connect from the surah container

- src/containers/Surah/index.js
Getting error locally, on Surah's label click action.
> JS error on surah click

- src/components/Ayah/index.js
- src/containers/Surah/index.js
I fixed this before, but somehow it got lost in a merge or something. A lot of people complaining on Zendesk.
> ensure play icon next to each ayah works

- src/components/Audioplayer/RepeatDropdown/index.js
> Fixes #411 - Repeat range bug

- src/helpers/buildAudio.js
- src/helpers/buildSegments.js
- src/redux/modules/audioplayer.js
This patch goes with https://github.com/quran/quran.com-api/pull/73,
which removes oggs and simplifies the response from the server.
> Simplify audio and segments building

- CONTRIBUTING.md
Nothing much just fixed the formatting of code blocks.
> Fix formatting of code blocks in CONTRIBUTING.md

- src/containers/Surah/index.js
fixes #458 
Thank you @ATouhou
> Surah Info close button not working

- src/styles/partials/_tooltip.scss
@sabeurthabti this is the commit that you missed when you merged #464 :)
> tooltip content is always ltr

- src/components/Ayah/index.js
- src/components/Ayah/style.scss
This pr closes [issue-499.](https://github.com/quran/quran.com-frontend/issues/499)
**Small screen:**
**Medium screen:**
**Large screen:**
> surah page layout breakdown fixed.

- src/components/Line/index.js
- src/components/Word/index.js
Not sure why this is the fix, but it's the fix!
> Fixes #598 Reading mode missing text

- src/containers/Error/index.js
Assalam O Alaikum ... Brother I have fixed the spacing bug on error page.
> Error page space bug fixed

- src/locale/en.js
Replaces some awkward wording with some less awkward wording.
> Copy-edit english locale

- src/components/GlobalSidebar/index.js
- src/components/GlobalSidebar/style.scss
Fixes https://github.com/quran/quran.com-frontend/issues/591
> Feature/back to home + css fix

- src/locale/tr.js
Turkish language locale file added
> tr.js - Turkish language locale file added

- src/components/ContentDropdown/index.js
- src/components/ReciterDropdown/index.js
- src/redux/actions/options.js
- src/redux/constants/options.js
- src/redux/modules/options.js
- src/server.js
- src/types/contentType.js
- src/types/index.js
Also:
Fixes https://github.com/quran/quran.com-frontend/issues/681
> Fixes #656 Translation dropdown

- src/components/Verse/index.js
This fix enables the pause button to stop the playback. See #615.
@mmahalwy @sharabash @sabeurthabti
> Fix pause toggle

- src/components/Home/QuickSurahs/index.js
- src/components/TopOptions/index.js
- src/components/TopOptions/style.scss
- src/containers/AyatulKursi/connect.js
- src/containers/AyatulKursi/index.js
- src/redux/actions/verses.js
- src/routes.js
- src/server/config/sitemap.js
Premise:
Ayatul Kursi is one of our highest queried by impression but is ranked poorly. This is an attempt to give it a little bump.
> Add Ayatul Kursi Page

- src/components/Share/index.js
- src/components/Verse/index.js
- src/containers/Surah/connect.js
- src/containers/Surah/index.js
- src/redux/actions/verses.js
- src/routes.js
- src/server/config/sitemap.js
* /2?translations=57  -> Transliteration 
* /1/1/28    -> Sahih International
* /1/1/ur-junagarri -> Slug for Urdu Jungarri
* /1/1/28,2 -> multiple translations
> Translation url

- src/components/Footer/PdfFooter/index.js
- src/containers/App/index.js
- src/routes.js
fix for https://github.com/quran/quran.com-frontend/issues/780
> pdf footer

- src/components/ContentDropdown/index.js
Fixes #718
Limits the number of translations selectable to a maximum of 10.
> Limit selection of translations (#718)

- src/styles/fonts/_fonts.scss
- src/styles/main.scss
fix for https://github.com/quran/quran.com-frontend/issues/808
> Moved font path to cdn, fixed direction for farsi

- LICENSE.md
Fixes https://github.com/quran/quran.com-frontend/issues/714
> Change license to reflect other projects

- package.json
- src/containers/Contact/index.js
- src/containers/Donations/index.js
- src/containers/MobileLanding/index.js
- src/helpers/StringHelpers.js
- src/helpers/setLocal.js
- src/helpers/tafsirs.js
- src/locale/ar.js
- src/locale/en.js
- src/locale/fr.js
- src/locale/id.js
- src/locale/nl.js
- src/locale/tr.js
- src/locale/ur.js
This builds on top of #838. See last 2 commits for new additions.
Same idea -- simple changes, nothing major, just making code a little cleaner in some places, even if it has no user-facing effects.
See comments for more info on changes (not going to repeat on changes from #838.
> Simple refactorizations (v3).

- src/styles/partials/_surah_names.scss
Fixes the Surah Alignment issue #828. This is my first pull request to this repo so if I screwed something up, let me know insha'Allah and I'll fix it.
> Fixes Arabic Surah Alignment Issue 828

- src/components/Footer/index.js
small edit don't need to fork right?
> keep the date current

- src/components/Footer/index.js
Automatically updating copyright year.
> Dynamic Footer Year

- src/helpers/StringHelpers.js
- src/utils/constants.js
Assalamualaikum
This is pull request for issue [855](https://github.com/quran/quran.com-frontend/issues/855)
I assume that the unintended mismatch is on the imported files.
> Fix mismatch import / export required files / funtion

- src/config.js
@naveed-ahmad ,I added fa: 'فارسی'  to available locales.
Thank you
> Just added fa: 'فارسی' to config

- .github/ISSUE_TEMPLATE.md
Related issue: https://github.com/quran/quran.com-frontend/issues/896
- [x ] Manually tested
- [x ] Prettier & ESLint were run
> added issue template #896

- src/components/Translation/index.js
Translation with footnote could have html as well, this isn't user generated data so xss isn't possible.
> fixed translation

- src/containers/Home/index.js
- src/redux/actions/verses.js
Moving Home container to a better place
> Fix up Home container

- src/redux/actions/fontFace.js
- src/redux/actions/juzs.js
- src/redux/actions/options.js
- src/redux/actions/search.js
- src/redux/actions/suggest.js
- src/redux/constants/fontFace.js
- src/redux/constants/juzs.js
- src/redux/constants/options.js
- src/redux/constants/search.js
- src/redux/constants/suggest.js
- src/redux/reducers/fontFaces.js
- src/redux/reducers/juzs.js
- src/redux/reducers/options.js
- src/redux/reducers/searchResults.js
- src/redux/reducers/suggestResults.js
- src/redux/reducers/verses.js
- tests/redux/actions/chapters.test.js
- tests/redux/actions/fontFace.test.js
- tests/redux/actions/juzs.test.js
- tests/redux/actions/options.test.js
- tests/redux/actions/search.test.js
- tests/redux/actions/suggest.test.js
- tests/redux/reducers/fontFaces.test.js
- tests/redux/reducers/juzs.test.js
- tests/redux/reducers/options.test.js
- tests/redux/reducers/searchResults.test.js
- tests/redux/reducers/suggestResults.test.js
Migrate more reducers and actions to redux actions and define
> Migrate more reducers and actions to redux actions and define

- src/redux/create.js
> Fix modules/reducer bug

- package-lock.json
- package.json
- src/components/Audioplayer/index.js
- src/components/GlobalNav/Surah/index.js
- src/components/SmartBanner/index.js
- src/components/Verse/index.js
- src/containers/App/index.js
- src/containers/AyatulKursi/index.js
- src/containers/ChapterInfo/index.js
- src/containers/Home/index.js
- src/containers/Surah/index.js
- src/containers/VerseTafsir/index.js
- src/routes.js
- webpack/dev.config.js
Brekdown bundles
After:
```Version: webpack 2.7.0
Time: 11988ms
Asset     Size  Chunks                    Chunk Names
Copy-chunk.js  11.1 kB      26  [emitted]         Copy
images/background.jpg  17.6 kB          [emitted]
images/logo-lg-w.png  20.1 kB          [emitted]
images/madinah.jpg   167 kB          [emitted]
images/makkah.jpg   270 kB          [emitted]  [big]
images/mockup-desktop@2x.png   564 kB          [emitted]  [big]
GlobalNavSurah-chunk.js   218 kB    0, 5  [emitted]         GlobalNavSurah
Surah-chunk.js   242 kB       1  [emitted]         Surah
Mobile-chunk.js  22.8 kB       2  [emitted]         Mobile
Contact-chunk.js  5.23 kB       3  [emitted]         Contact
Donations-chunk.js  5.98 kB       4  [emitted]         Donations
GlobalNav-chunk.js   175 kB       5  [emitted] …
```
> Breakdown modules further

- src/components/Footer/index.stories.js
- src/components/Home/ChapterItem/index.stories.js
- src/components/Home/ChaptersList/index.stories.js
- src/components/Home/LastVisit/index.stories.js
- src/components/Home/QuickSurahs/index.stories.js
- src/components/SurahsDropdown/index.stories.js
Fix storybook with react-router
> Fix storybook with react-router

- README.md
Change readme to remove the slack link
> Change readme to remove the slack link

- .circleci/config.yml
- .eslintrc
- package-lock.json
- package.json
- src/components/ChapterInfoPanel/index.js
- src/components/ChapterInfoPanel/spec.js
- src/components/Navbars/index.js
- src/components/Routes/index.js
- src/components/SurahInfo/index.js
- src/containers/App/index.js
- src/containers/ChapterInfo/index.js
- src/containers/ChapterInfoPanelContainer/index.js
- src/containers/Surah/connect.js
- src/containers/Surah/index.js
- src/redux/actions/chapterInfos.js
- src/redux/actions/chapters.js
- src/redux/constants/chapterInfos.js
- src/redux/constants/chapters.js
- src/redux/reducers/chapterInfos.js
- src/redux/reducers/chapters.js
- src/redux/reducers/index.js
- src/routes.js
- src/server.js
- tests/__mocks__/fileMock.js
- tests/fixtures/chapterInfos.js
- tests/fixtures/chapters.js
- tests/redux/actions/chapters.test.js
- tests/redux/reducers/chapters.test.js
- tests/routes.test.js
> Move chapter info to container

- package-lock.json
- package.json
- src/components/ChapterInfoPanel/index.js
- src/components/ChaptersDropdown/index.js
- src/components/ComponentLoader/index.js
- src/shapes/ChapterInfoShape.js
- src/shapes/ChapterShape.js
> Cleanups to proptypes and shapes

- README.md
> link to contribution is broken

- .circleci/config.yml
- internal/webpack/configFactory.js
> Fix happypack path

- src/containers/Donations/index.js
Fixes https://github.com/quran/quran.com-frontend/issues/853
> Remove tilt donations link

- src/components/Audioplayer/index.js
- src/containers/Chapter/index.js
Audio Player been navigating properly. A solution for #525 
https://youtu.be/9JgYW1xKhzY
> Fixing Next Surah issue

- internal/webpack/configFactory.js
- src/server/middleware/reactApplication/ServerHTML.tsx
- src/server/middleware/reactApplication/getClientBundleEntryAssets.js
> Fix assets.json bug for dev

- internal/webpack/configFactory.js
- src/server/middleware/reactApplication/ServerHTML.tsx
- src/server/middleware/reactApplication/getClientBundleEntryAssets.js
> Use assets plugin

- config/values.js
- internal/webpack/configFactory.js
- package-lock.json
- package.json
- src/client/index.tsx
- src/components/Audioplayer.tsx
- src/redux/actions/_tests_/footNotes.test.ts
- src/redux/actions/footNotes.ts
- src/server/middleware/reactApplication/ServerHTML.tsx
> Staging broken due to scripts not loading

- src/components/App.tsx
- src/components/Audioplayer.tsx
- src/components/Navbar.tsx
- src/components/Navbars.tsx
- src/components/Translation.tsx
- src/components/Verse.tsx
- src/components/Word.tsx
- src/components/audioplayer/Wrapper.tsx
- src/components/dls/navbar/Nav.tsx
- src/components/settings/FontSizeOptions.tsx
- src/components/settings/NightModeToggle.tsx
- src/containers/AudioplayerContainer.tsx
- src/containers/NavbarContainer.tsx
- src/containers/VerseContainer.tsx
- src/containers/WordContainer.tsx
- src/containers/_tests_/AudioplayerContainer.test.tsx
- src/containers/_tests_/VerseContainer.test.tsx
- src/containers/_tests_/WordContainer.test.tsx
- src/styles/nightmode.scss
- src/theme.ts
Where do you prefer to place the site language toggle button in the home page?
> Fixing Night Mode [WIP]

- src/components/App.tsx
- src/components/Audioplayer.tsx
- src/components/Navbar.tsx
- src/components/Translation.tsx
- src/components/Verse.tsx
- src/components/Word.tsx
- src/components/audioplayer/Wrapper.tsx
- src/components/dls/navbar/Nav.tsx
- src/components/settings/FontSizeOptions.tsx
- src/containers/AudioplayerContainer.tsx
- src/containers/NavbarContainer.tsx
- src/containers/TranslationContainer.tsx
- src/containers/_tests_/AudioplayerContainer.test.tsx
> Prettifying my code with Prettier

- src/components/Verse.tsx
- src/components/Word.tsx
- src/containers/WordContainer.tsx
- src/containers/_tests_/WordContainer.test.tsx
This was the issue: https://youtu.be/jnK3tw6_WG4
> Fixing the black color while playing issue

- src/locale/_tests_/locale.test.ts
- src/locale/ar.ts
Add tests to ensure all locale files are matching and no texts are missing across locales
Currently, some texts are missing and while we can fix it right now, who knows in the future some more will be missing. See commits for examples of texts that are currently missing.
Very new here, so please let me know if there is a better way to do this.
- [ x ] Unit tests written
- [ x ] Manually tested
- [ x ] Prettier & ESLint were run
> WIP: Fix/imran  test locales

- config/values.js
- src/locale/index.ts
- src/locale/it.ts
> Added italian language

- src/locale/fa.ts
some fix on persian translation
> some fix on persian translation

- README.md
Since this repo is stale now, and the main focus is in the quran.com-frontend-v2 branch, it's necessary to make sure that contributors are on the same page.
> Add note about the current repo

- .env
- src/helpers/Html.js
> Add Google Tag Manager
